name: netlib.re自动登录

on:
  schedule:
    - cron: "45 3 3 */3 *"  # 每三个月的第三天的 3:45 运行（UTC时间）
  workflow_dispatch:

jobs:
  auto-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Playwright
        run: |
          pip install --upgrade pip
          pip install -r netlib-login/requirements.txt
          playwright install chromium

      - name: Run Keep Alive Login
        env:
          NETLIB_ACCOUNTS: ${{ secrets.NETLIB_ACCOUNTS }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python -u netlib-login/autologin.py
